version: 0.2

phases:
  pre_build:
    commands:
      - | 
        GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
        
      - echo $GIT_BRANCH

  build:
    commands:
      # if [ "$GIT_BRANCH" = "" ] ; then
      #     GIT_BRANCH="$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')";
      #   fi

artifacts:
  files: imagedefinitions.json