version: 0.2
phases:
  pre_build:
    commands:
      - text_file="file.txt"
      - |
        if [ ! -f "$text_file" ]; then
          echo "Text file not found at $text_file"
          exit 1
        fi
      - ls
      - echo "---------------------------"
      - |
        while IFS= read -r LINE || [ -n "$LINE" ]; do
          echo "Line from file: $LINE";
          echo "---------------------------"
          echo "---------------------------"
          cd $LINE
          echo "Contents of text.txt:"
          cat "text.txt"
          echo "---------------------------"
          echo "---------------------------"
          cd ..
        done < "$text_file"