version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - GIT_BRANCH="$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')";
  build:
    commands:
      - echo "Building..."
  post_build:
    commands:
      - echo "Post build steps..."
      - echo $GIT_BRANCH
      - if [ "$GIT_BRANCH" = "master" ]; then
           echo "Building for master branch";
           echo Build started on `date`
           newimagename=rl-branch-test-master
           echo $newimagename
        fi

