version: 0.2
env:
  variables:
    BRANCH_NAME: $CODEBUILD_WEBHOOK_TRIGGER
phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building..."
  post_build:
    commands:
      - echo "Post build steps..."

if [ "$BRANCH_NAME" == "master" ]: then
  post_build:
    commands:
      - echo "Deploying to production..."
fi