version: 0.2
env:
  variables:
    BRANCH_NAME: $(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)
phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building..."
  post_build:
    commands:
      - echo "Post build steps..."
      - echo $BRANCH_NAME
      - if [ "$BRANCH_NAME" = "main" ]; then
           echo "Building for main branch";
           echo Build started on `date`
           newimagename=rl-branch-test-main
           echo $newimagename
        fi

