version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - BRANCH_NAME=$(git symbolic-ref HEAD --short 2>/dev/null)
  build:
    commands:
      - echo "Building..."
  post_build:
    commands:
      - echo "Post build steps..."
      - echo $BRANCH_NAME
      - if [ "$BRANCH_NAME" = "main" ]; then
           echo "Building for main branch";
           echo Build started on `date`
           newimagename=rl-branch-test-main
           echo $newimagename
        fi

