version: 0.2

phases:
  pre_build:
    commands:
      - | 
        GIT_BRANCH="$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')";
        
      - echo $GIT_BRANCH

  build:
    commands:
      - |
        if [ "$GIT_BRANCH" = "main" ]; then
          echo "Building for main branch"
          echo "Build started on $(date)"
          newimagename=rl-branch-test-main
          echo $newimagename
          text_file="file.txt"

          # Check if the text file exists
          if [ ! -f "$text_file" ]; then
            echo "Text file not found at $text_file"
            exit 1
          fi
          ls
          echo "---------------------------"
          while IFS= read -r LINE || [ -n "$LINE" ]; do
            echo "Line from file: $LINE";
            echo "---------------------------"
            echo "---------------------------"
            cd $LINE
            echo "Contents of text.txt:"
            cat "text.txt"
            echo "---------------------------"
            echo "---------------------------"
            cd ..
          done < "$text_file"
                    
        fi

artifacts:
  files: imagedefinitions.json